[project]
name = "chatty"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.34.0",
    "redis[hiredis]>=5.2.0",
    "pydantic-settings>=2.7.0",
]
